metadata:
  name: Default
  description: Template profile for Honeycomb Bravo

buttons:
  # rev:
  # nav:
  hdg:
    single_click:
      - command_str: "AirbusFBW/PushHDGSel"
    double_click:
      - command_str: "AirbusFBW/PullHDGSel"
  ias:
    single_click:
      - command_str: "AirbusFBW/PushSPDSel"
    double_click:
      - command_str: "AirbusFBW/PullSPDSel"
  alt:
    single_click:
      - command_str: "AirbusFBW/PushAltitude"
    double_click:
      - command_str: "AirbusFBW/PullAltitude"
  vs:
    single_click:
      - command_str: "AirbusFBW/PushVSSel"
    double_click:
      - command_str: "AirbusFBW/PullVSSel"
  apr:
    single_click:
      - command_str: "AirbusFBW/APPRbutton"
    double_click:
      - command_str: "AirbusFBW/APPRbutton"
  ap:
    single_click:
      - command_str: "toliss_airbus/ap1_push"
    double_click:
      - command_str: "toliss_airbus/ap2_push"


knobs:
  ap_hdg:
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/heading_dial_deg_mag_pilot"
  ap_alt:
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/altitude_dial_ft"
  ap_vs:
    datarefs:
      - dataref_str: "AirbusFBW/FCUVSKnobRotation"
  ap_ias:
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/airspeed_dial_kts_mach"
  ap_crs:
  # repurpose to qnh

leds:
  hdg:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/heading_mode"
        operator: "=="
        threshold: 1

  nav:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/nav_status"
        operator: "=="
        threshold: 1

  apr:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/approach_status"
        operator: "=="
        threshold: 1

  rev:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/backcourse_status"
        operator: "=="
        threshold: 1

  alt:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/altitude_hold_status"
        operator: "=="
        threshold: 1

  vs:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/vvi_status"
        operator: "=="
        threshold: 1

  ias:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/autothrottle_on"
        operator: "=="
        threshold: 1

  ap:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/autopilot/servos_on"
        operator: ">"
        threshold: 0.01

  gear:
    profile_type: led
    datarefs:
      - dataref_str: "sim/flightmodel2/gear/deploy_ratio"
        operator: "!="
        threshold: 0



  master_warn:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/annunciators/master_warning"
        operator: ">"
        threshold: 0.01

  fire:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/annunciators/engine_fires"
        operator: ">"
        threshold: 0.01

  oil_low_pressure:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/annunciators/oil_pressure_low"
        operator: "<"
        threshold: 0.075

  fuel_low_pressure:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/annunciators/fuel_pressure_low"
        operator: "<"
        threshold: 0.075

  anti_ice:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/annunciators/pitot_heat"
        operator: ">"
        threshold: 0.01

  eng_starter:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/engine/actuators/starter_hit"
        operator: ">"
        threshold: 0.01

  apu:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/electrical/APU_running"
        operator: ">"
        threshold: 0.01

  master_caution:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/annunciators/master_caution"
        operator: ">"
        threshold: 0.01

  vacuum:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/annunciators/low_vacuum"
        operator: "<"
        threshold: 1

  hydro_low_pressure:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/annunciators/hydraulic_pressure"
        operator: "<"
        threshold: 2500

  aux_fuel_pump:
    profile_type: led
    condition: "all"
    datarefs:
      - dataref_str: "sim/cockpit2/fuel/transfer_pump_right"
        operator: ">"
        threshold: 0.01
      - dataref_str: "sim/cockpit2/fuel/transfer_pump_left"
        operator: ">"
        threshold: 0.01

  parking_brake:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/controls/parking_brake_ratio"
        operator: "=="
        threshold: 1

  volt_low:
    profile_type: led
    datarefs:
      - dataref_str: "sim/cockpit2/annunciators/low_voltage"
        operator: "<"
        threshold: -80

  doors:
    profile_type: led
    datarefs:
      - dataref_str: "sim/flightmodel2/misc/door_open_ratio"
        operator: ">"
        threshold: 0.9


data:
  bus_voltage:
    datarefs:
      - dataref_str: "sim/cockpit2/electrical/bus_volts"
        operator: ">"
        threshold: 0.01

  retractable_gear:
    datarefs:
      - dataref_str: "sim/aircraft/gear/acf_gear_retract"
        operator: "!="
        threshold: 0

  ap_state:
    profile_type: data
    data:
      - dataref_str: "sim/cockpit2/autopilot/autopilot_state"