// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProfileFiles() {
  return window['go']['main']['App']['GetProfileFiles']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetXplane() {
  return window['go']['main']['App']['GetXplane']();
}

export function GetXplaneDataref(arg1) {
  return window['go']['main']['App']['GetXplaneDataref'](arg1);
}
