// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';

export function GetProfileFiles():Promise<Array<string>>;

export function GetProfiles():Promise<Array<pkg.Profile>>;

export function Greet(arg1:string):Promise<pkg.Profile>;
