name: Release

# Controls when the workflow will run
on:
  push:
    pull_request:
    tags:
      - 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-13

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable # Specify toolchain (e.g., stable, beta, nightly)
          override: true
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: |
          export VERSION=${GITHUB_REF##*/} 
          VERSION=${GITHUB_REF##*/} make mac win -j 2
          
          TAG=${GITHUB_REF##*/}
          cp ${{ github.workspace }}/skunkcrafts_updater.cfg ${{ github.workspace }}/build/xa-honeycomb/
          cp -r ${{ github.workspace }}/profiles ${{ github.workspace }}/build/xa-honeycomb/
          sed -i '' "s/REPLACE_ME/${TAG}/g" ${{ github.workspace }}/build/xa-honeycomb/skunkcrafts_updater.cfg
          
          root=$(pwd)
          cd ${{ github.workspace }}/build/ && zip -r xa-honeycomb.zip xa-honeycomb && cd $root

      - run: |
          cp -r ${{ github.workspace }}/build/xa-honeycomb/ release/
          # create crc32 checksum for all values and write to skunkcrafts_updater_whitelist.txt
          # format is <filename>|<crc32 checksum>
          # include subdirectories
          rm -f release/skunkcrafts_updater_whitelist.txt
          find release -type f ! \( -name '*skunkcrafts_updater*' -o -path '*skunkcrafts_updater*' \) -print0 | while IFS= read -r -d '' file; do
            checksum_hex=$(crc32 "$file")
            # Convert hex checksum to uint32 decimal
            checksum_decimal=$((16#$checksum_hex))
            # Remove "release/" prefix from $file
            modified_file="${file#release/}"
            echo "$modified_file|$checksum_decimal" >> release/skunkcrafts_updater_whitelist.txt
          done
          touch release/skunkcrafts_updater_blacklist.txt
          
          TAG=${GITHUB_REF##*/}
          TARGET_BRANCH="release"
          # if TAG contains -
          git checkout -b ${TARGET_BRANCH}
          git add .
          git commit -m "new ${TARGET_BRANCH} - ${TAG}"
          git push -f -u origin ${TARGET_BRANCH}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}/README.md
          files: |
            ${{ github.workspace }}/build/xa-honeycomb.zip
          prerelease: ${{ contains(github.ref_name, '-') }}
